config/routes.rb
Rails.application.routes.draw do
  devise_for :users
devise_scope :user do
get "/login" => "devise/sessions#new"
get "/logout" => "devise/sessions#destroy"
get "/signup" => "devise/registrations#new"
end


  resources :locations, :rooms, :fotos, :indexpages#, add: :description_of_payment
  root 'indexpages#index'
  get "description_of_payment" => "indexpages#description_of_payment"
  # get "description_of_payment", :to => redirect('layouts/description-of-payment.html')
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/indexpage.rb
class Indexpage < ApplicationRecord
# 	EMAIL = 'dbachinin@ya.ru'
# 	validate :email_is_true

# def email_is_true
# 		return true if email.include?(EMAIL)
# 	end
end

app/controllers/indexpages_controller.rb
class IndexpagesController < ApplicationController
  before_action :set_indexpage, only: [:show, :edit, :update, :destroy]
before_action :authenticate_user!, :except => [:index, :description_of_payment]

  # GET /indexpages
  # GET /indexpages.json
  def description_of_payment
  end
  def index
    @indexpages = Indexpage.all
    @index = Indexpage.first
    @descr = @index.description.split('#').first
    @hello = @index.description.split('#')[1]
    @address = @index.description.split('#')[2]
  end

  # GET /indexpages/1
  # GET /indexpages/1.json
  def show
  end

  # GET /indexpages/new
  def new
    @indexpage = Indexpage.new
  end

  # GET /indexpages/1/edit
  def edit
  end

  # POST /indexpages
  # POST /indexpages.json
  def create
    @indexpage = Indexpage.new(indexpage_params)

    respond_to do |format|
      if @indexpage.save
        format.html { redirect_to @indexpage, notice: 'Indexpage was successfully created.' }
        format.json { render :show, status: :created, location: @indexpage }
      else
        format.html { render :new }
        format.json { render json: @indexpage.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /indexpages/1
  # PATCH/PUT /indexpages/1.json
  def update
    respond_to do |format|
      if @indexpage.update(indexpage_params)
        format.html { redirect_to @indexpage, notice: 'Indexpage was successfully updated.' }
        format.json { render :show, status: :ok, location: @indexpage }
      else
        format.html { render :edit }
        format.json { render json: @indexpage.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /indexpages/1
  # DELETE /indexpages/1.json
  def destroy
    @indexpage.destroy
    respond_to do |format|
      format.html { redirect_to indexpages_url, notice: 'Indexpage was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_indexpage
      @indexpage = Indexpage.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def indexpage_params
      params.require(:indexpage).permit(:description, :foto)
    end
end

app/helpers/indexpages_helper.rb
module IndexpagesHelper
end

app/views/indexpages/_form.html.erb
<%= form_with(model: indexpage, local: true) do |form| %>
  <% if indexpage.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(indexpage.errors.count, "error") %> prohibited this indexpage from being saved:</h2>

      <ul>
      <% indexpage.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :indexpage_description %>
  </div>

  <div class="field">
    <%= form.label :foto %>
    <%= form.text_field :foto, id: :indexpage_foto %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/indexpages/description_of_payment.html.erb
<%= render file: 'layouts/_description-of-payment.html.erb'%>

<%= link_to 'Back', root_path %>

app/views/indexpages/edit.html.erb
<h1>Editing Indexpage</h1>

<%= render 'form', indexpage: @indexpage %>

<%= link_to 'Show', @indexpage %> |
<%= link_to 'Back', indexpages_path %>

app/views/indexpages/index.html.erb
    <div id="mainVisual">
       <div id="slideshow5a0fef22563f8" class="slideshow"> 
       <% item = 0%>
<% @index.foto.split(',').each do |foto| %>
<% item +=1%>
     <style type="text/css">
        #slideshow5a0fef22563f8 div.item<%=item%>{background-image:url(media/foto/__thumbs_1400_900_crop/<%=foto%>);}
        @media only screen and ( max-width: 767px ) { #slideshow5a0fef22563f8 div.item<%=item%>{background-image:url(media/foto/__thumbs_740_561_crop/<%=foto%>);} }
      </style>

      <div class="slide item<%=item%>"></div>
   <%end%>
    <!--<img alt="" src="" class="slide" />-->
       </div>

<div id="controls">
  <div class="cycle-prev cycle-nav"></div>
  <div class="cycle-next cycle-nav"></div>
</div>

<!-- jQuery Scripts for Slide show -->

<script type="text/javascript">
jQuery(document).ready(function() {
  jQuery('.slideshow').cycle({
    slides: '> div',
    fx:     'fade',
    speed:  300,
    timeout: 7000,
    prev: '.cycle-prev',
    next: '.cycle-next',
    slideResize:0,
    easeIn:  'swing',
    easeOut: 'swing',
    swipe: true
  });

});
</script>

    </div>  <!-- END #mainVisual -->

    <div class="checkrates">

    </div>

<div id="content" class="home">
  <div class="wrapper">
    <h1 class="mainTitle"><span class="homepage-title"><%= @hello.split('|').first%></span></h1>
    <h2 class="seoh2"><%= @hello.split('|')[1]%></h2>
    <div class="contentButton">
      <a href="#" class="button_bg open"></a>
<!--       <a href="#" class="close"></a> -->
    </div>  <!-- END .contentButton -->
    <div class="introText"><%= raw @index.description.split('#')[0] %>
</div> <!-- END .introText -->
  </div>  <!-- END .wrapper -->
</div>  <!-- END #content -->


<!-- PAGE SPECIFIC SCRIPTS -->
<script type="text/javascript">
$(document).ready(function(){

  $("#content").find('.introText').jScrollPane({mouseWheelSpeed: 30, verticalGutter: 30, autoReinitialise: true});

  $("#content .contentButton a ").click(function () {
    var el = $(this);
    if(el.parents().eq(1).hasClass("open")){
      el.parents().eq(1).removeClass("open");
    }else{
      el.parents().eq(1).addClass("open");
    }
  });
});

</script>

app/views/indexpages/new.html.erb
<h1>New Indexpage</h1>

<%= render 'form', indexpage: @indexpage %>

<%= link_to 'Back', indexpages_path %>

app/views/indexpages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @indexpage.description %>
</p>

<p>
  <strong>Foto:</strong>
  <%= @indexpage.foto %>
</p>

<%= link_to 'Edit', edit_indexpage_path(@indexpage) %> |
<%= link_to 'Back', indexpages_path %>