config/routes.rb
Rails.application.routes.draw do
  devise_for :users
devise_scope :user do
get "/login" => "devise/sessions#new"
get "/logout" => "devise/sessions#destroy"
get "/signup" => "devise/registrations#new"
end


  resources :locations, :rooms, :fotos, :indexpages#, add: :description_of_payment
  root 'indexpages#index'
  get "description_of_payment" => "indexpages#description_of_payment"
  # get "description_of_payment", :to => redirect('layouts/description-of-payment.html')
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/room.rb
class Room < ApplicationRecord
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: [:show, :edit, :update, :destroy]
before_action :authenticate_user!, :except => [:index, :description_of_payment]


  def description_of_payment
  end
  # GET /rooms
  # GET /rooms.json
  def index
    @rooms = Room.all
    @index = Indexpage.first
    @descr = @index.description.split('#').first
    @hello = @index.description.split('#')[1]
    @address = @index.description.split('#')[2]
  end

  # GET /rooms/1
  # GET /rooms/1.json
  def show
  end

  # GET /rooms/new
  def new
    @room = Room.new
  end

  # GET /rooms/1/edit
  def edit
  end

  # POST /rooms
  # POST /rooms.json
  def create
    @room = Room.new(room_params)

    respond_to do |format|
      if @room.save
        format.html { redirect_to @room, notice: 'Room was successfully created.' }
        format.json { render :show, status: :created, location: @room }
      else
        format.html { render :new }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rooms/1
  # PATCH/PUT /rooms/1.json
  def update
    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to @room, notice: 'Room was successfully updated.' }
        format.json { render :show, status: :ok, location: @room }
      else
        format.html { render :edit }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1
  # DELETE /rooms/1.json
  def destroy
    @room.destroy
    respond_to do |format|
      format.html { redirect_to rooms_url, notice: 'Room was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room
      @room = Room.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def room_params
      params.require(:room).permit(:name, :description, :price, :foto)
    end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/_form.html.erb
<%= form_with(model: room, local: true) do |form| %>
  <% if room.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(room.errors.count, "error") %> prohibited this room from being saved:</h2>

      <ul>
      <% room.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :room_name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :room_description %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price, id: :room_price %>
  </div>

  <div class="field">
    <%= form.label :foto %>
    <%= form.text_field :foto, id: :room_foto %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/rooms/description_of_payment.html.erb
<%= render 'layouts/description_of_payment'%>

<%= link_to 'Back', root_path %>

app/views/rooms/edit.html.erb
<h1>Editing Room</h1>

<%= render 'form', room: @room %>

<%= link_to 'Show', @room %> |
<%= link_to 'Back', rooms_path %>

app/views/rooms/index.html.erb
<div id="subVisual">
  <div id="slideshow5a0ff997c1c18" class="slideshow">       <style type="text/css">
    #slideshow5a0ff997c1c18 div.item1{background-image:url(media/__thumbs_1400_502_crop/IMG_6252.JPG);}
    @media only screen and ( max-width: 767px ) { #slideshow5a0ff997c1c18 div.item1{background-image:none;} }
  </style>

  <div class="slide item1"></div>
  <!--<img alt="" src="" class="slide" />-->
  <style type="text/css">
    #slideshow5a0ff997c1c18 div.item2{background-image:url(media/__thumbs_1400_502_crop/IMG_6252.JPG);}
    @media only screen and ( max-width: 767px ) { #slideshow5a0ff997c1c18 div.item2{background-image:none;} }
  </style>

  <div class="slide item2"></div>
  <!--<img alt="" src="" class="slide" />-->
  <style type="text/css">
    #slideshow5a0ff997c1c18 div.item3{background-image:url(media/__thumbs_1400_502_crop/IMG_6333.JPG);}
    @media only screen and ( max-width: 767px ) { #slideshow5a0ff997c1c18 div.item3{background-image:none;} }
  </style>

  <div class="slide item3"></div>
  <!--<img alt="" src="" class="slide" />-->
  <style type="text/css">
    #slideshow5a0ff997c1c18 div.item4{background-image:url(media/__thumbs_1400_502_crop/IMG_6448.JPG);}
    @media only screen and ( max-width: 767px ) { #slideshow5a0ff997c1c18 div.item4{background-image:none;} }
  </style>

  <div class="slide item4"></div>
  <!--<img alt="" src="" class="slide" />-->
  <style type="text/css">
    #slideshow5a0ff997c1c18 div.item5{background-image:url(media/__thumbs_1400_502_crop/IMG_6346.JPG);}
    @media only screen and ( max-width: 767px ) { #slideshow5a0ff997c1c18 div.item5{background-image:none;} }
  </style>

  <div class="slide item5"></div>
  <!--<img alt="" src="" class="slide" />-->
  <style type="text/css">
    #slideshow5a0ff997c1c18 div.item6{background-image:url(media/__thumbs_1400_502_crop/IMG_6240.JPG);}
    @media only screen and ( max-width: 767px ) { #slideshow5a0ff997c1c18 div.item6{background-image:none;} }
  </style>

  <div class="slide item6"></div>
  <!--<img alt="" src="" class="slide" />-->
  <style type="text/css">
    #slideshow5a0ff997c1c18 div.item7{background-image:url(media/__thumbs_1400_502_crop/IMG_6287.JPG);}
    @media only screen and ( max-width: 767px ) { #slideshow5a0ff997c1c18 div.item7{background-image:none;} }
  </style>

  <div class="slide item7"></div>
  <!--<img alt="" src="" class="slide" />-->
</div>

<div id="controls">
  <div class="cycle-prev cycle-nav"></div>
  <div class="cycle-next cycle-nav"></div>
</div>

<!-- jQuery Scripts for Slide show -->

<script type="text/javascript">
  jQuery(document).ready(function() {
    jQuery('#subVisual .slideshow').cycle({
      slides: '> div',
      fx:     'fade',
      speed:  300,
      timeout: 7000,
      prev: '.cycle-prev',
      next: '.cycle-next',
      slideResize:0,
      easeIn:  'swing',
      easeOut: 'swing',
      swipe: true
    });

  });
</script>

</div>  <!-- END #mainVisual -->

<div class="checkrates">
  <div class="text-wrap">
  </div>
  <!-- <a class="check booking-link" href="https://www.booking.com/hotel/ru/voroniezh.ru.html?aid=964694&app_hotel_id=1519641&checkin=2017-12-30&checkout=2017-12-31&from_sn=android&group_adults=2&group_children=0&label=Share-VnsuLq%401510997643&no_rooms=1&req_adults=2&req_children=0&room1=A%2CA#rt-lightbox-open-RD151964116" target="_blank">Показать цены</a> -->   </div>

  <div id="content" class="subpage">

    <div class="content-wrapper">

      <div class="detail">
        <span class="text">Номера</span>
      </div>

      <div class='has-sidebar-wrapper'>
        <h1 class="mainTitle">Номера</h1>
        <h2 class="seoh2">Насладитесь современными номерами рядом с Чёрным Морем</h2>
        <div class="first-content">
          <p>До пляжа можно дойти всего за 1 минуту. Отель «Золотое кольцо» с террасой и видом на сад расположен в Адлере, в 300 м от океанариума Sochi Discovery World Aquarium и в 70 м от побережья Черного моря. К услугам гостей бесплатный Wi-Fi.</p>

          <p>Все номера оснащены кондиционером и телевизором, а в некоторых из них обустроен гостиный уголок. В собственной ванной комнате установлен душ.</p>

          <p>Рядом с отелем «Золотое кольцо» работают различные кафе и рестораны. Поблизости также находятся магазины, бары, боулинг-центр и теннисный корт.</p>

          <p>В отеле работает экскурсионное бюро.</p>

          <p>Отель «Золотое кольцо» находится в 600 м от дельфинария «Акватория» и в 1,2 км от аквапарка «Амфибиус». Расстояние до центра Адлера составляет 1 км. Железнодорожный вокзал «Андлер» находится в 2,5 км от отеля «Золотое кольцо», а международный аэропорт Адлер-Сочи — в 5 км. </p>

          <p>арам особенно нравится расположение — они оценили проживание в этом районе для поездки вдвоем на 8,9.</p>

          <p>Мы говорим на вашем языке!</p>

          <p>Golden Ring Hotel: гостей здесь принимают с 3 нояб. 2015.</p>
        </div>
        <div class="second-content">

        </div>


        <div id="mod_pukkaSimpleRooms" class="moduleOutput viewList">
          <!---RUBY-->
          <div class="moduleBody">
            <%
            def get_pictures(id,crop)
              @files = []
              Dir.foreach(Room.find(id).foto + crop) do |foto|
               @files.push(Room.find(id).foto[7..-1] + crop + foto) if foto.include?("JPG")
             end
             return @files

             end%>

             <%cnt = 0%>
             <% @rooms.each do |room| %>
                        <% cnt+=1 %>
             <div class="moduleItemTab acc_<%=cnt%>">
              <div class="category item<%=cnt.to_s+ ' ' + room.name + ' '%> <%=p 'selected' if cnt == 1%>">
                <h3 class="accordionTitleModule"><%=room.name%><span class="button"></span></h3>
                <div class="accordion-content">
                  <div class="module<%="23"+cnt.to_s%>Nav tabs">
                    <ul class="resp-tabs-list">
                      <li id='tab<%=cnt+1%>'><span><%=room.name%></span></li>
                      <style>
                        .module<%="23"+cnt.to_s%>Nav.tabs .resp-tabs-list li{width:calc((100% / 1) - .6em); max-width: 150px;}
                      </style>
                    </ul>
                  </div>

                  <div class="mod_content resp-tabs-container">
                    <div  class="itemPreview alt" id="item<%=cnt+1%>">
                      <div class="itemPreviewImageSection">
                        <div class="icon"></div>
                        <div class="prevImage prevImage-<%="2"+cnt.to_s%>"></div>
                        <div class="nextImage nextImage-<%="2"+cnt.to_s%>"></div>



                        <div class="roomSlideshow-<%="2"+cnt.to_s%>" data-cycle-swipe="true">
                          <% thumbs_1400_502 = get_pictures(room.id,'__thumbs_1400_502_crop/') %>
                          <% thumbs_222_119 = get_pictures(room.id,'__thumbs_222_119_crop/') %>
                          <% 0.upto(thumbs_222_119.count-1).each do |fot| %>
                          <a class='slide' href="<%=thumbs_1400_502[fot]%>" rel="slideShow-<%="2"+cnt.to_s%>">
                            <img src="<%=thumbs_222_119[fot]%>" class="slide" width="222" height="119" />
                          </a>
                          <%end%>
                          <%thumbs_1400_502 =[]%>
                          <%thumbs_222_119 = []%> 
                        </div><!-- END .roomSlideshow -->             </div><!-- END .itemPreviewImageSection -->

                        <div class='itemContent'>
                          <h3 class="itemContentTitle"><%=room.name%></h3>
                          <span class="content"><p><%=room.description%></p></span>
                          <div class="read-more toggleContent">Узнать подробности</div>
                          <div class="read-less toggleContent">Скрыть подробности</div>
                        </div>
                        <div class="itemBottomContent">
                          <a class="booking-link button_bg" href="tel:+79184007026" target="_blank"><span class="booking-link-text">Узнайте цены сейчас!</span></a>           </div><!-- END .itemBottomContent -->

                          <script type='text/javascript'>
                            jQuery(function() {
                      if(jQuery().fancybox && $("#layout").css("float")!="none"){ //namespace check
                        var fancyBoxConf = {
                          'transitionIn'  : 'fade',
                          'transitionOut' : 'fade',
                          'speedIn':500,
                          'speedOut':500
                        };
                        $('a.slide[rel="slideShow-<%="2"+cnt.to_s%>"]').fancybox(fancyBoxConf);
                      }else{
                        $('img.slide').parent('.slide').removeAttr('href');
                      }


                      jQuery("#mod_pukkaSimpleRooms .category .itemPreview").each(function(){
                        jQuery(this).find('.icon').click(function(){
                          jQuery(jQuery(this).parent().find('a.slide.cycle-slide-active[rel="slideShow-<%="2"+cnt.to_s%>"]')).trigger('click');
                          return false;
                        });
                      });
                      jQuery('.roomSlideshow-<%="2"+cnt.to_s%>').cycle({
                        fx:     'fade',
                        speed:  '2000',
                        timeout: 7000,
                        slideResize:0,
                        prev: '.prevImage-<%="2"+cnt.to_s%>',
                        next: '.nextImage-<%="2"+cnt.to_s%>',
                        slides: '> a.slide'
                      });
                    });
                  </script>
                </div><!-- END  class="itemPreview alt" -->
              </div> <!--END accordion content -->
            </div><!-- END mod_content resp-tabs-container -->
          </div><!--END "category item<%=cnt.to_s+ ' ' + room.name + ' '%> <%=p 'selected' if cnt == 1%>" -->

        </div><!--END .moduleItemTab-->
        <%end%>

        <script type="text/javascript">

          jQuery(document).ready(function() {
            $('.moduleItemTab').easyResponsiveTabs({ closed: true });

            $('.read-more').click(function(){
              contentHeight = 0;
              $(this).parent().find("span.content").children().each(function(){ contentHeight += ($(this).outerHeight(true)); });
              $(this).parent().find('span.content').addClass("open").stop().animate({ height : contentHeight },200, function(){
                $(this).parent().find('span.content').css("height","auto");
              });
              $(this).hide();
              $(this).parent().addClass("open").find('.read-less').show();
            });
            $('.read-less').click(function(){
              $(this).parent().find('span.content').stop().animate({ height : '5em' },200).removeClass("open");
              $(this).hide();
              $(this).parent().removeClass("open").find('.read-more').show();
            });

          });
        </script>

      </div>
    </div>

    
  </div><!-- end .content-wrapper -->


  <!-- </div> -->  <!-- END .wrapper -->
</div>  <!-- END #content -->
</div>
</div>

app/views/rooms/new.html.erb
<h1>New Room</h1>

<%= render 'form', room: @room %>

<%= link_to 'Back', rooms_path %>

app/views/rooms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @room.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @room.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @room.price %>
</p>

<p>
  <strong>Foto:</strong>
  <%= @room.foto %>
</p>

<%= link_to 'Edit', edit_room_path(@room) %> |
<%= link_to 'Back', rooms_path %>