config/routes.rb
Rails.application.routes.draw do
  devise_for :users
devise_scope :user do
get "/login" => "devise/sessions#new"
get "/logout" => "devise/sessions#destroy"
get "/signup" => "devise/registrations#new"
end


  resources :locations, :rooms, :fotos, :indexpages#, add: :description_of_payment
  root 'indexpages#index'
  get "description_of_payment" => "indexpages#description_of_payment"
  # get "description_of_payment", :to => redirect('layouts/description-of-payment.html')
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/foto.rb
class Foto < ApplicationRecord
end

app/controllers/fotos_controller.rb
class FotosController < ApplicationController
  before_action :set_foto, only: [:show, :edit, :update, :destroy]
before_action :authenticate_user!, :except => [:index, :description_of_payment]


  def description_of_payment
  end
  # GET /fotos
  # GET /fotos.json
  def index
    @fotos = Foto.all
    idd = params[:itemid]||@fotos.first.id
    @item = Foto.find(idd)
    @index = Indexpage.first
    @descr = @index.description.split('#').first
    @hello = @index.description.split('#')[1]
    @address = @index.description.split('#')[2]
  end

  # GET /fotos/1
  # GET /fotos/1.json
  def show
  end

  # GET /fotos/new
  def new
    @foto = Foto.new
  end

  # GET /fotos/1/edit
  def edit
  end

  # POST /fotos
  # POST /fotos.json
  def create
    @foto = Foto.new(foto_params)

    respond_to do |format|
      if @foto.save
        format.html { redirect_to @foto, notice: 'Foto was successfully created.' }
        format.json { render :show, status: :created, location: @foto }
      else
        format.html { render :new }
        format.json { render json: @foto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fotos/1
  # PATCH/PUT /fotos/1.json
  def update
    respond_to do |format|
      if @foto.update(foto_params)
        format.html { redirect_to @foto, notice: 'Foto was successfully updated.' }
        format.json { render :show, status: :ok, location: @foto }
      else
        format.html { render :edit }
        format.json { render json: @foto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fotos/1
  # DELETE /fotos/1.json
  def destroy
    @foto.destroy
    respond_to do |format|
      format.html { redirect_to fotos_url, notice: 'Foto was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_foto
      @foto = Foto.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def foto_params
      params.require(:foto).permit(:foto, :description, :item)
    end
end

app/helpers/fotos_helper.rb
module FotosHelper
end

app/views/fotos/_form.html.erb
<%= form_with(model: foto, local: true) do |form| %>
  <% if foto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(foto.errors.count, "error") %> prohibited this foto from being saved:</h2>

      <ul>
      <% foto.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :foto %>
    <%= form.text_field :foto, id: :foto_foto %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description, id: :foto_description %>
  </div>

  <div class="field">
    <%= form.label :item %>
    <%= form.text_field :item, id: :foto_item %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/fotos/description_of_payment.html.erb
<%= render 'layouts/description_of_payment'%>

<%= link_to 'Back', root_path %>

app/views/fotos/edit.html.erb
<h1>Editing Foto</h1>

<%= render 'form', foto: @foto %>

<%= link_to 'Show', @foto %> |
<%= link_to 'Back', fotos_path %>

app/views/fotos/index.html.erb
<div id="gallery-holder">
  <div id="gallery-content">
    <div id="mod_pukkaGalleries" class="moduleOutput viewItem">

      <div class="moduleBody">
        <%count=0%>
        <% @fotos.find(@item.id).foto.split(',').each do |f|%>
        <% count +=1%>
        <style type="text/css">
          #mod_pukkaGalleries .gallery-slides .item<%=count%>{background-image:url(media/__thumbs_1400_900_crop/<%=f%>);}
          #mod_pukkaGalleries a.image<%=count%> span.pager-ico{width:90px;height:58px;background-image: url(media/__thumbs_90_58_crop/<%=f%>);}
          @media only screen and ( max-width: 767px ) {
            #mod_pukkaGalleries .gallery-slides .item<%=count%>{background-image:url(media/__thumbs_740_561_crop/<%=f%>);}
            #mod_pukkaGalleries a.image<%=count%> span.pager-ico{background-image:none;}
          }
        </style>
        <%end%>
        <div class="gallery-slides">
          <div class="cycle-slideshow" data-cycle-slides="> .slide"
            data-cycle-fx="fade"
            data-cycle-pager="#gallery-pager-mobile"
            data-cycle-pager-template="<span class='pager-number'>{{slideNum}} of 6</span>"
            data-cycle-timeout="7000"
            data-cycle-speed="500"
            data-cycle-prev=".cycle-prev, #gallery-pager .cycleThumb-prev"
            data-cycle-next=".cycle-next, #gallery-pager .cycleThumb-next"
            data-cycle-swipe=true
            data-cycle-carousel-visible="1">
            <%1.upto(count).each do |i|%>
            <%if @fotos.find(@item.id).description.include?(i.to_s)%>
            <%@fotos.find(@item.id).description.split('/').each {|ii|@desk = ii if ii.include?(i.to_s)}%>
            <div class="image-slide slide item<%=@desk.split(':')[0]%>">       
              <div class="imageTitle"><span class="imageDescription"><%=@desk.split(':')[1]%></span></div>
              <div class="imageTitle-mobile"><%=@desk.split(':')[2]%></div>
              <div class="gradient-bg"></div>
            </div>
            <%else%>
            <div class="image-slide slide item<%=i%>"></div>
            <%end%>
            <%end%>            
          </div>

          <div id="controls">
            <div class="cycle-prev cycle-nav"></div>
            <div class="cycle-next cycle-nav"></div>
            <!--<a id="fullscreen-button"></a>-->
          </div>

          <div id="gallery-pager-mobile" class="cycle-pager">

          </div>
        </div>

        <div id="gallery-components">
          <div id="gallery-components-wrapper" class="section-wrapper">
            <div id="sub-menu">
              <h3 class="section">Фотогалерея</h3>
              <div class="gallerynav">
                <span></span>

                <div class="gallery-content-menu">
                  <%@fotos.each do |item|%>  
                  <% if item.id == @item.id %>
                  <div  class="galleryOptions button_bg first active"><%= link_to @fotos.find(item.id).item, fotos_path(itemid: item) %></div> 
                  <%else%>    
                  <div  class="galleryOptions button_bg"><%= link_to item.item, fotos_path(itemid: item) %></div>     
                  <%end%>
                  <%end%>   
                </div><!-- end .gallery-content-menu -->
              </div><!-- end .gallerynav -->
<!--               <span class="select-button"></span>
              <select class="main-content-menu" onchange="if (this.value) window.location.href=this.value">       <option class="first active option" value="http://golden-ring.ru.com/photos_131-ru.html" selected="selected">Экстерьер</option>       <option class=" option" value="http://golden-ring.ru.com/photos_111-ru.html" >Отель</option>        <option class=" option" value="http://golden-ring.ru.com/photos_141-ru.html" >Номера</option></select> -->
              <span class="select-button"></span>

              <select class="main-content-menu" onchange="if (this.value) window.location.href=this.value"> 
                <%= @fotos.each do |photo| %>
                <% if photo.id == @item.id %>
                <option class="first active option" value="<%=fotos_path(itemid: photo) %>"><%=@fotos.find(photo.id).item%></option> 
                <%else%>
                <option class=" option" value="<%=fotos_path(itemid: photo.id) %>"><%=photo.item%></option>
                <%end%>
                <%end%>
                </select>
              <script type="text/javascript">
                jQuery(document).ready(function(){

                  $("span.select-button").text($("option.active").text());

                  var valueTxt = $('.galleryOptions.active a').text();
                  if( valueTxt.length != 0 ){
                    $('.gallerynav span').text(valueTxt);
                  }



                  $('.gallerynav').click(function(){
                    $('.gallery-content-menu').slideToggle("200","easeOutBack");
                    $(".gallerynav").toggleClass("on");
                  });


                });
              </script>

            </div>              <div id="gallery-pager" class="cycle-pager">                  <a class="cycleThumb-prev button_bg"></a>
            <a class="cycleThumb-next button_bg"></a>
            <div id="cycle-2" class="cycle-slideshow"
            data-cycle-slides="> a"
            data-cycle-timeout="7000"
            data-cycle-speed="500"
            data-cycle-prev="#gallery-pager .cycleThumb-prev, .cycle-prev"
            data-cycle-next="#gallery-pager .cycleThumb-next, .cycle-next"
            data-cycle-fx="carousel"
            data-cycle-carousel-visible="4"
            data-cycle-carousel-fluid="false"
            data-allow-wrap="true"
            s                        >
            <%count.times do |c|%>    <a class="thumb-image non-active image<%=c+1%>">
            <span class="pager-ico"></span>
          </a>
          <%end%>
        </div>

      </div>
    </div>
    <!-- MODULE SPECIFIC SCRIPTS -->
    <script type="text/javascript">
      jQuery(document).ready(function(){
    // Advance the other slideshow
    var slideshows = $('.cycle-slideshow').on( function(e, opts) {
      slideshows.not(this).cycle('goto', opts.currSlide);
    });

    // Synchronize the slideshow with the carousel
    $('#cycle-2 .cycle-slide').click(function(){
      var index = $('#cycle-2').data('cycle.API').getSlideIndex(this);
      slideshows.cycle('goto', index);
    });
  });
</script>



</div>
</div>
</div>
</div>

app/views/fotos/new.html.erb
<h1>New Foto</h1>

<%= render 'form', foto: @foto %>

<%= link_to 'Back', fotos_path %>

app/views/fotos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Foto:</strong>
  <%= @foto.foto %>
</p>

<p>
  <strong>Description:</strong>
  <%= @foto.description %>
</p>

<p>
  <strong>Item:</strong>
  <%= @foto.item %>
</p>

<%= link_to 'Edit', edit_foto_path(@foto) %> |
<%= link_to 'Back', fotos_path %>